# Define the files for network training and evaluation in the toml format.
#
# Give an array of train files and evaluation files.
# If the network has multiple inputs, mark each seperate dataset with [[input]].
#
# Example format:
# -----------------------------
# [[input]]
# train_files = [
# "path/to/train_file_1_inputx.h5",
# "path/to/train_file_2_inputx.h5",
# ]
#
# evaluation_files = [
# "path/to/test_file_1_inputx.h5",
# ]
#
# [[input]]
# train_files = [
# "path/to/train_file_1_inputy.h5",
# "path/to/train_file_2_inputy.h5",
# ]
#
# evaluation_files = [
# "path/to/test_file_1_inputy.h5",
# ]
# -----------------------------

[[input]]
train_files = [
"/project/antares/enriqueh/data/orcasong_output/4dTo4d/xyzc/JTE_KM3Sim_gseagen_elec-CC_3-100GeV-1_1E6-1bin-3_0gspec_ORCA115_9m_2016_1_xyzc.h5",
"/project/antares/enriqueh/data/orcasong_output/4dTo4d/xyzc/JTE_KM3Sim_gseagen_elec-CC_3-100GeV-1_1E6-1bin-3_0gspec_ORCA115_9m_2016_2_xyzc.h5",
"/project/antares/enriqueh/data/orcasong_output/4dTo4d/xyzc/JTE_KM3Sim_gseagen_elec-CC_3-100GeV-1_1E6-1bin-3_0gspec_ORCA115_9m_2016_3_xyzc.h5",
"/project/antares/enriqueh/data/orcasong_output/4dTo4d/xyzc/JTE_KM3Sim_gseagen_elec-CC_3-100GeV-1_1E6-1bin-3_0gspec_ORCA115_9m_2016_4_xyzc.h5",
"/project/antares/enriqueh/data/orcasong_output/4dTo4d/xyzc/JTE_KM3Sim_gseagen_elec-CC_3-100GeV-1_1E6-1bin-3_0gspec_ORCA115_9m_2016_6_xyzc.h5",
"/project/antares/enriqueh/data/orcasong_output/4dTo4d/xyzc/JTE_KM3Sim_gseagen_elec-CC_3-100GeV-1_1E6-1bin-3_0gspec_ORCA115_9m_2016_7_xyzc.h5",
"/project/antares/enriqueh/data/orcasong_output/4dTo4d/xyzc/JTE_KM3Sim_gseagen_elec-CC_3-100GeV-1_1E6-1bin-3_0gspec_ORCA115_9m_2016_8_xyzc.h5",
"/project/antares/enriqueh/data/orcasong_output/4dTo4d/xyzc/JTE_KM3Sim_gseagen_elec-CC_3-100GeV-1_1E6-1bin-3_0gspec_ORCA115_9m_2016_9_xyzc.h5",
"/project/antares/enriqueh/data/orcasong_output/4dTo4d/xyzc/JTE_KM3Sim_gseagen_elec-CC_3-100GeV-1_1E6-1bin-3_0gspec_ORCA115_9m_2016_10_xyzc.h5",
"/project/antares/enriqueh/data/orcasong_output/4dTo4d/xyzc/JTE_KM3Sim_gseagen_elec-NC_3-100GeV-3_4E6-1bin-3_0gspec_ORCA115_9m_2016_1_xyzc.h5",
"/project/antares/enriqueh/data/orcasong_output/4dTo4d/xyzc/JTE_KM3Sim_gseagen_elec-NC_3-100GeV-3_4E6-1bin-3_0gspec_ORCA115_9m_2016_2_xyzc.h5",
"/project/antares/enriqueh/data/orcasong_output/4dTo4d/xyzc/JTE_KM3Sim_gseagen_elec-NC_3-100GeV-3_4E6-1bin-3_0gspec_ORCA115_9m_2016_3_xyzc.h5",
"/project/antares/enriqueh/data/orcasong_output/4dTo4d/xyzc/JTE_KM3Sim_gseagen_elec-NC_3-100GeV-3_4E6-1bin-3_0gspec_ORCA115_9m_2016_4_xyzc.h5",
"/project/antares/enriqueh/data/orcasong_output/4dTo4d/xyzc/JTE_KM3Sim_gseagen_elec-NC_3-100GeV-3_4E6-1bin-3_0gspec_ORCA115_9m_2016_6_xyzc.h5",
"/project/antares/enriqueh/data/orcasong_output/4dTo4d/xyzc/JTE_KM3Sim_gseagen_elec-NC_3-100GeV-3_4E6-1bin-3_0gspec_ORCA115_9m_2016_7_xyzc.h5",
"/project/antares/enriqueh/data/orcasong_output/4dTo4d/xyzc/JTE_KM3Sim_gseagen_elec-NC_3-100GeV-3_4E6-1bin-3_0gspec_ORCA115_9m_2016_8_xyzc.h5",
"/project/antares/enriqueh/data/orcasong_output/4dTo4d/xyzc/JTE_KM3Sim_gseagen_elec-NC_3-100GeV-3_4E6-1bin-3_0gspec_ORCA115_9m_2016_9_xyzc.h5",
"/project/antares/enriqueh/data/orcasong_output/4dTo4d/xyzc/JTE_KM3Sim_gseagen_elec-NC_3-100GeV-3_4E6-1bin-3_0gspec_ORCA115_9m_2016_10_xyzc.h5",
]

validation_files = [
"/project/antares/enriqueh/data/orcasong_output/4dTo4d/xyzc/JTE_KM3Sim_gseagen_elec-CC_3-100GeV-1_1E6-1bin-3_0gspec_ORCA115_9m_2016_5_xyzc.h5",
"/project/antares/enriqueh/data/orcasong_output/4dTo4d/xyzc/JTE_KM3Sim_gseagen_elec-NC_3-100GeV-3_4E6-1bin-3_0gspec_ORCA115_9m_2016_5_xyzc.h5",
]


#[[input]]
#train_files = [
#"/home/woody/capn/mppi033h/Data/ORCA_JTE_NEMOWATER/ip_images_1-100GeV/4dTo4d/xyzc_time_-250+500_w_gf_31b/concatenated/muon-cc_and_elec-cc-nc/elec-CC_and_elec-NC_and_muon-CC_xyzc_train_file_0_shuffled_0.h5",
#"/home/woody/capn/mppi033h/Data/ORCA_JTE_NEMOWATER/ip_images_1-100GeV/4dTo4d/xyzc_time_-250+500_w_gf_31b/concatenated/muon-cc_and_elec-cc-nc/elec-CC_and_elec-NC_and_muon-CC_xyzc_train_file_1_shuffled_0.h5",
#"/home/woody/capn/mppi033h/Data/ORCA_JTE_NEMOWATER/ip_images_1-100GeV/4dTo4d/xyzc_time_-250+500_w_gf_31b/concatenated/muon-cc_and_elec-cc-nc/elec-CC_and_elec-NC_and_muon-CC_xyzc_train_file_2_shuffled_0.h5",
#"/home/woody/capn/mppi033h/Data/ORCA_JTE_NEMOWATER/ip_images_1-100GeV/4dTo4d/xyzc_time_-250+500_w_gf_31b/concatenated/muon-cc_and_elec-cc-nc/elec-CC_and_elec-NC_and_muon-CC_xyzc_train_file_3_shuffled_0.h5",
#"/home/woody/capn/mppi033h/Data/ORCA_JTE_NEMOWATER/ip_images_1-100GeV/4dTo4d/xyzc_time_-250+500_w_gf_31b/concatenated/muon-cc_and_elec-cc-nc/elec-CC_and_elec-NC_and_muon-CC_xyzc_train_file_4_shuffled_0.h5",
#]
#
#evaluation_files = [
#"/home/woody/capn/mppi033h/Data/ORCA_JTE_NEMOWATER/ip_images_1-100GeV/4dTo4d/xyzc_time_-250+500_w_gf_31b/concatenated/muon-cc_and_elec-cc-nc/elec-CC_and_elec-NC_and_muon-CC_xyzc_test_file_0_shuffled_0.h5",
#"/home/woody/capn/mppi033h/Data/ORCA_JTE_NEMOWATER/ip_images_1-100GeV/4dTo4d/xyzc_time_-250+500_w_gf_31b/concatenated/muon-cc_and_elec-cc-nc/elec-CC_and_elec-NC_and_muon-CC_xyzc_test_file_1_shuffled_0.h5",
#]
#
#
